/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Part4(props) {
    const { nodes, materials } = useGLTF('/assets/model/part4.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                name="Plane"
                geometry={nodes.Plane.geometry}
                material={materials['Material.012']}
                position={[-31.95, 17.29, -57.39]}
                rotation={[0.6, -0.51, 0.32]}
                scale={[14.1, 4.81, 5.72]}
            />
        </group>
    );
}
