/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Character(props) {
    //   const group = useRef();
    const { nodes, materials } = useGLTF('/assets/model/test.glb');
    //   const { actions } = useAnimations(animations, group);
    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature">
                    <primitive object={nodes.mixamorigHips} />
                    <primitive object={nodes.Ctrl_Master} />
                    <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
                    <primitive object={nodes.Ctrl_Hand_IK_Left} />
                    <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
                    <primitive object={nodes.Ctrl_Hand_IK_Right} />
                    <primitive object={nodes.Ctrl_Foot_IK_Left} />
                    <primitive object={nodes.Ctrl_LegPole_IK_Left} />
                    <primitive object={nodes.Ctrl_Foot_IK_Right} />
                    <primitive object={nodes.Ctrl_LegPole_IK_Right} />
                    <skinnedMesh
                        name="Ch42_Sneakers"
                        geometry={nodes.Ch42_Sneakers.geometry}
                        material={materials.Ch42_Body}
                        skeleton={nodes.Ch42_Sneakers.skeleton}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/test.glb');
