/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from 'react';
import { useGLTF, Merged } from '@react-three/drei';

const context = createContext();
export function Part4Instances({ children, ...props }) {
    const { nodes } = useGLTF('/startuptn/codissia/stall.glb');
    const instances = useMemo(
        () => ({
            B: nodes.B30,
            R: nodes.R15,
            R1: nodes.R14,
            B1: nodes.B104,
            Cube2: nodes.Cube069,
            B2: nodes.B358
        }),
        [nodes]
    );
    return (
        <Merged meshes={instances} {...props}>
            {(instances) => <context.Provider value={instances} children={children} />}
        </Merged>
    );
}

export default function Part4(props) {
    const { nodes, materials } = useGLTF('/startuptn/codissia/stall.glb');

    const instances = useContext(context);
    return (
        <group {...props} dispose={null}>
            <instances.B name="B30" position={[-148.43, 2.5, -61.76]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B76" position={[-123.28, 2.5, -57.13]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B26" position={[-124.35, 2.5, -64.14]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B31" position={[-148.1, 2.5, -44.75]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B54" position={[-136.52, 2.5, 49.53]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B19" position={[-98.2, 2.5, -55.82]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B16" position={[-96.49, 2.5, -39.62]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B58" position={[-95.22, 2.5, 38.28]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B1" position={[-88.08, 2.5, 38.56]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B77" position={[-120.11, 2.5, 40.79]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B68" position={[-103.45, 2.5, -49.52]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C7" position={[-80.66, 2.5, -100.56]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C18" position={[-120.5, 2.5, -103.99]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C19" position={[-124.08, 2.5, -103.63]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C20" position={[-127.69, 2.5, -103.22]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B2" position={[-88.42, 2.5, 35.09]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B3" position={[-88.77, 2.5, 31.63]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B4" position={[-89.11, 2.5, 28.17]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B5" position={[-89.45, 2.5, 24.7]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B6" position={[-89.79, 2.5, 21.24]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B7" position={[-90.13, 2.5, 17.78]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B8" position={[-90.48, 2.5, 14.32]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B9" position={[-90.82, 2.5, 10.85]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B10" position={[-91.16, 2.5, 7.39]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B11" position={[-91.5, 2.5, 3.93]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B59" position={[-95.56, 2.5, 34.82]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B60" position={[-95.9, 2.5, 31.35]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B61" position={[-96.24, 2.5, 27.89]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B62" position={[-96.58, 2.5, 24.43]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B63" position={[-96.92, 2.5, 20.96]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B64" position={[-97.27, 2.5, 17.5]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B65" position={[-97.61, 2.5, 14.04]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B66" position={[-97.95, 2.5, 10.58]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B67" position={[-98.29, 2.5, 7.11]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B29" position={[-144.97, 2.5, -62.1]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B28" position={[-141.51, 2.5, -62.44]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B27" position={[-138.04, 2.5, -62.79]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B75" position={[-122.94, 2.5, -53.67]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B74" position={[-122.6, 2.5, -50.21]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B73" position={[-122.26, 2.5, -46.74]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B72" position={[-121.91, 2.5, -43.28]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B71" position={[-121.57, 2.5, -39.82]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B70" position={[-121.23, 2.5, -36.35]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B69" position={[-120.89, 2.5, -32.89]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B25" position={[-120.89, 2.5, -64.48]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B24" position={[-117.42, 2.5, -64.82]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B23" position={[-113.96, 2.5, -65.16]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B22" position={[-110.5, 2.5, -65.51]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B21" position={[-107.04, 2.5, -65.85]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B20" position={[-103.57, 2.5, -66.19]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B32" position={[-147.76, 2.5, -41.28]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B33" position={[-147.42, 2.5, -37.82]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B34" position={[-147.07, 2.5, -34.36]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B35" position={[-146.73, 2.5, -30.89]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B36" position={[-146.39, 2.5, -27.43]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B37" position={[-146.05, 2.5, -23.97]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B38" position={[-145.71, 2.5, -20.5]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B39" position={[-145.36, 2.5, -17.04]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B40" position={[-145.02, 2.5, -13.58]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B41" position={[-144.68, 2.5, -10.12]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B42" position={[-144.34, 2.5, -6.65]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B43" position={[-144, 2.5, -3.19]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B44" position={[-143.65, 2.5, 0.27]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B45" position={[-143.31, 2.5, 3.74]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B46" position={[-142.97, 2.5, 7.2]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B47" position={[-142.63, 2.5, 10.66]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B48" position={[-142.29, 2.5, 14.13]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B49" position={[-141.94, 2.5, 17.59]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B50" position={[-141.6, 2.5, 21.05]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B51" position={[-141.26, 2.5, 24.52]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B52" position={[-140.92, 2.5, 27.98]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B53" position={[-140.58, 2.5, 31.44]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B55" position={[-133.06, 2.5, 49.19]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B56" position={[-129.59, 2.5, 48.85]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B57" position={[-126.13, 2.5, 48.51]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B18" position={[-97.85, 2.5, -52.36]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B17" position={[-97.51, 2.5, -48.9]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B15" position={[-96.15, 2.5, -36.16]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B14" position={[-95.8, 2.5, -32.7]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B13" position={[-95.46, 2.5, -29.23]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B12" position={[-95.12, 2.5, -25.77]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B78" position={[-120.45, 2.5, 37.33]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="B79" position={[-120.79, 2.5, 33.86]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C6" position={[-80.32, 2.5, -97.1]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C5" position={[-79.98, 2.5, -93.64]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C4" position={[-79.64, 2.5, -90.17]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C3" position={[-79.3, 2.5, -86.71]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C2" position={[-78.95, 2.5, -83.25]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C1" position={[-78.61, 2.5, -79.79]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C17" position={[-116.94, 2.5, -104.34]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C16" position={[-113.55, 2.5, -104.68]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C15" position={[-110.11, 2.5, -105.01]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C14" position={[-106.66, 2.5, -105.36]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C13" position={[-103.24, 2.5, -105.69]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C12" position={[-99.75, 2.5, -106.04]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C11" position={[-96.25, 2.5, -106.38]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C10" position={[-92.64, 2.5, -106.74]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C9" position={[-89.17, 2.5, -107.08]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.B name="C8" position={[-85.67, 2.5, -107.43]} rotation={[0, -1.47, 0]} scale={[1.45, 0.43, 1.45]} />
            <instances.R name="R15" position={[-109.55, 2.5, -25.38]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R21" position={[-106.34, 2.5, 7.11]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R37" position={[-120.28, 2.5, -91.32]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R36" position={[-119.12, 2.5, -79.57]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R32" position={[-94.2, 2.5, -82.03]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R16" position={[-109.09, 2.5, -20.74]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R17" position={[-108.63, 2.5, -16.09]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R18" position={[-108.17, 2.5, -11.44]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R19" position={[-107.71, 2.5, -6.8]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R20" position={[-107.26, 2.5, -2.15]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R22" position={[-105.88, 2.5, 11.75]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R23" position={[-105.42, 2.5, 16.4]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R24" position={[-104.96, 2.5, 21.05]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R25" position={[-104.51, 2.5, 25.69]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R26" position={[-104.05, 2.5, 30.34]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R27" position={[-103.59, 2.5, 34.99]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R28" position={[-103.13, 2.5, 39.63]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R34" position={[-112, 2.5, -92.14]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R33" position={[-103.72, 2.5, -92.96]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R31" position={[-95.43, 2.5, -93.78]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R30" position={[-87.15, 2.5, -94.59]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R35" position={[-110.84, 2.5, -80.38]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <instances.R name="R29" position={[-85.92, 2.5, -82.84]} rotation={[0, 0.1, 0]} scale={[2.03, 0.43, 2.03]} />
            <mesh
                name="Cube067"
                castShadow
                receiveShadow
                geometry={nodes.Cube067.geometry}
                material={materials['Material.005']}
                position={[-102.63, 2.5, -81.19]}
                rotation={[0, 0.1, 0]}
                scale={[2.03, 0.43, 2.03]}
            />
            <mesh
                name="Cube068"
                castShadow
                receiveShadow
                geometry={nodes.Cube068.geometry}
                material={materials['Material.005']}
                position={[-124.53, 2.5, -0.25]}
                rotation={[0, 0.1, 0]}
                scale={[1.45, 0.43, 2.08]}
            />
            <instances.R1 name="R14" position={[-118.52, 2.5, -24.48]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R8" position={[-115.29, 2.5, 8.22]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R13" position={[-118.06, 2.5, -19.84]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="r12" position={[-117.61, 2.5, -15.2]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R11" position={[-117.15, 2.5, -10.56]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R10" position={[-116.69, 2.5, -5.92]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R9" position={[-116.23, 2.5, -1.28]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R7" position={[-114.84, 2.5, 12.86]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R6" position={[-114.38, 2.5, 17.5]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R5" position={[-113.92, 2.5, 22.14]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R4" position={[-113.46, 2.5, 26.78]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R3" position={[-113, 2.5, 31.42]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R2" position={[-112.54, 2.5, 36.06]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.R1 name="R1" position={[-112.09, 2.5, 40.7]} rotation={[0, 0.1, 0]} scale={[2.73, 0.43, 2.08]} />
            <instances.B1 name="B104" position={[-130.09, 2.5, -56.28]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B98" position={[-126.85, 2.5, -23.42]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B105" position={[-121.15, 2.5, 29.84]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B107" position={[-123.49, 2.5, 19.79]} rotation={[-Math.PI, 1.47, -Math.PI]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B106" position={[-128.11, 2.5, 20.25]} rotation={[-Math.PI, 1.47, -Math.PI]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B109" position={[-107.55, 2.5, -49.15]} rotation={[-Math.PI, 1.47, -Math.PI]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B108" position={[-112.17, 2.5, -48.69]} rotation={[-Math.PI, 1.47, -Math.PI]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B103" position={[-129.63, 2.5, -51.64]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B102" position={[-129.17, 2.5, -47]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B101" position={[-128.72, 2.5, -42.36]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B100" position={[-128.26, 2.5, -37.72]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B99" position={[-127.8, 2.5, -33.08]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B97" position={[-126.39, 2.5, -18.78]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B96" position={[-125.93, 2.5, -14.14]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B95" position={[-125.47, 2.5, -9.5]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.B1 name="B94" position={[-125.01, 2.5, -4.86]} rotation={[0, 0.1, 0]} scale={[1.45, 0.43, 2.08]} />
            <instances.Cube2 name="Cube069" position={[-128.48, 2.5, -91.08]} rotation={[0, 0.1, 0]} scale={[2.41, 0.43, 2.41]} />
            <instances.Cube2 name="Cube449" position={[-110.15, 2.5, -56.59]} rotation={[Math.PI, -0.1, 0]} scale={[-4.82, -0.9, -5.6]} />
            <instances.Cube2 name="Cube450" position={[-126.51, 2.5, 11.65]} rotation={[Math.PI, -0.1, 0]} scale={[-4.82, -0.9, -5.6]} />
            <instances.B2 name="B358" position={[-143.08, 2.5, -56.07]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B335" position={[-137.55, 2.5, -56.62]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B334" position={[-135.26, 2.5, -56.85]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B298" position={[-139.87, 2.5, -23.61]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B299" position={[-134.35, 2.5, -24.16]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B322" position={[-132.06, 2.5, -24.39]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B194" position={[-102.5, 2.5, -27.3]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B217" position={[-100.21, 2.5, -27.53]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B249" position={[-120.03, 2.5, -58.35]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B286" position={[-136.29, 2.5, 9.09]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B233" position={[-112.67, 2.5, -42.89]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B232" position={[-110.41, 2.5, -43.11]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B223" position={[-104.41, 2.5, -43.7]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B222" position={[-102.15, 2.5, -43.92]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B254" position={[-104.2, 2.5, -61.9]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B270" position={[-127.22, 2.5, 43.28]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B255" position={[-125.04, 2.5, 43.06]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B359" position={[-139.82, 2.5, 43.25]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B360" position={[-140.06, 2.5, 40.85]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C92" position={[-129.23, 2.5, -86.77]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C91" position={[-126.78, 2.5, -87.01]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C82" position={[-121.07, 2.5, -87.63]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C77" position={[-118.7, 2.5, -87.87]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C68" position={[-112.69, 2.5, -88.46]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C63" position={[-110.52, 2.5, -88.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C56" position={[-104.79, 2.5, -89.63]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C51" position={[-102.36, 2.5, -89.87]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C44" position={[-96.26, 2.5, -90.47]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C39" position={[-93.9, 2.5, -90.7]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C30" position={[-88.09, 2.5, -91.28]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C257" position={[-85.8, 2.5, -91.5]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C97" position={[-125.29, 2.5, -71.9]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B357" position={[-142.85, 2.5, -53.73]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B356" position={[-142.61, 2.5, -51.39]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B355" position={[-142.38, 2.5, -49.05]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B354" position={[-142.15, 2.5, -46.7]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B353" position={[-141.92, 2.5, -44.36]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B352" position={[-141.69, 2.5, -42.02]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B351" position={[-141.46, 2.5, -39.68]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B350" position={[-141.23, 2.5, -37.33]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B349" position={[-141, 2.5, -34.99]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B348" position={[-140.76, 2.5, -32.65]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B347" position={[-140.53, 2.5, -30.31]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B336" position={[-137.32, 2.5, -54.28]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B337" position={[-137.09, 2.5, -51.93]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B338" position={[-136.86, 2.5, -49.59]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B339" position={[-136.63, 2.5, -47.25]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B340" position={[-136.39, 2.5, -44.91]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B341" position={[-136.16, 2.5, -42.57]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B342" position={[-135.93, 2.5, -40.22]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B343" position={[-135.7, 2.5, -37.88]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B344" position={[-135.47, 2.5, -35.54]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B345" position={[-135.24, 2.5, -33.2]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B346" position={[-135.01, 2.5, -30.85]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B333" position={[-135.03, 2.5, -54.5]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B332" position={[-134.8, 2.5, -52.16]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B331" position={[-134.57, 2.5, -49.82]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B330" position={[-134.34, 2.5, -47.48]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B329" position={[-134.11, 2.5, -45.13]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B328" position={[-133.87, 2.5, -42.79]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B327" position={[-133.64, 2.5, -40.45]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B326" position={[-133.41, 2.5, -38.11]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B325" position={[-133.18, 2.5, -35.76]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B324" position={[-132.95, 2.5, -33.42]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B323" position={[-132.72, 2.5, -31.08]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B297" position={[-139.64, 2.5, -21.27]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B296" position={[-139.41, 2.5, -18.93]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B295" position={[-139.18, 2.5, -16.59]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B294" position={[-138.95, 2.5, -14.24]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B293" position={[-138.72, 2.5, -11.9]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B292" position={[-138.48, 2.5, -9.56]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B291" position={[-138.25, 2.5, -7.22]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B290" position={[-138.02, 2.5, -4.87]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B289" position={[-137.79, 2.5, -2.53]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B288" position={[-137.56, 2.5, -0.19]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B287" position={[-137.33, 2.5, 2.15]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B300" position={[-134.11, 2.5, -21.82]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B301" position={[-133.88, 2.5, -19.47]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B302" position={[-133.65, 2.5, -17.13]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B303" position={[-133.42, 2.5, -14.79]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B304" position={[-133.19, 2.5, -12.45]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B305" position={[-132.96, 2.5, -10.1]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B306" position={[-132.73, 2.5, -7.76]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B307" position={[-132.5, 2.5, -5.42]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B308" position={[-132.26, 2.5, -3.08]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B309" position={[-132.03, 2.5, -0.74]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B310" position={[-131.8, 2.5, 1.61]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B321" position={[-131.83, 2.5, -22.04]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B320" position={[-131.59, 2.5, -19.7]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B319" position={[-131.36, 2.5, -17.36]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B318" position={[-131.13, 2.5, -15.02]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B317" position={[-130.9, 2.5, -12.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B316" position={[-130.67, 2.5, -10.33]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B315" position={[-130.44, 2.5, -7.99]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B314" position={[-130.21, 2.5, -5.65]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B313" position={[-129.98, 2.5, -3.3]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B312" position={[-129.74, 2.5, -0.96]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B311" position={[-129.51, 2.5, 1.38]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B195" position={[-102.27, 2.5, -24.96]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B196" position={[-102.04, 2.5, -22.62]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B197" position={[-101.8, 2.5, -20.28]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B198" position={[-101.57, 2.5, -17.93]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B199" position={[-101.34, 2.5, -15.59]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B200" position={[-101.11, 2.5, -13.25]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B201" position={[-100.88, 2.5, -10.91]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B202" position={[-100.65, 2.5, -8.56]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B203" position={[-100.42, 2.5, -6.22]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B204" position={[-100.19, 2.5, -3.88]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B205" position={[-99.95, 2.5, -1.54]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B216" position={[-99.98, 2.5, -25.19]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B215" position={[-99.75, 2.5, -22.84]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B214" position={[-99.52, 2.5, -20.5]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B213" position={[-99.28, 2.5, -18.16]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B212" position={[-99.05, 2.5, -15.82]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B211" position={[-98.82, 2.5, -13.48]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B210" position={[-98.59, 2.5, -11.13]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B209" position={[-98.36, 2.5, -8.79]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B208" position={[-98.13, 2.5, -6.45]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B207" position={[-97.9, 2.5, -4.11]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B206" position={[-97.67, 2.5, -1.76]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B248" position={[-119.79, 2.5, -56.01]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B247" position={[-119.56, 2.5, -53.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B246" position={[-119.33, 2.5, -51.32]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B245" position={[-119.1, 2.5, -48.98]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B244" position={[-118.87, 2.5, -46.64]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B243" position={[-118.64, 2.5, -44.3]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B242" position={[-118.41, 2.5, -41.95]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B241" position={[-118.18, 2.5, -39.61]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B240" position={[-117.94, 2.5, -37.27]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B239" position={[-117.71, 2.5, -34.93]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B238" position={[-117.48, 2.5, -32.58]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B285" position={[-136.06, 2.5, 11.43]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B284" position={[-135.83, 2.5, 13.77]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B283" position={[-135.6, 2.5, 16.11]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B282" position={[-135.37, 2.5, 18.46]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B281" position={[-135.14, 2.5, 20.8]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B280" position={[-134.91, 2.5, 23.14]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B279" position={[-134.68, 2.5, 25.48]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B278" position={[-134.44, 2.5, 27.83]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B277" position={[-134.21, 2.5, 30.17]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B276" position={[-133.98, 2.5, 32.51]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B275" position={[-133.75, 2.5, 34.85]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B274" position={[-133.52, 2.5, 37.19]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B273" position={[-133.29, 2.5, 39.54]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B272" position={[-133.06, 2.5, 41.88]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B271" position={[-132.83, 2.5, 44.22]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B234" position={[-112.44, 2.5, -40.54]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B235" position={[-112.21, 2.5, -38.2]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B236" position={[-111.97, 2.5, -35.86]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B237" position={[-111.74, 2.5, -33.52]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B231" position={[-110.18, 2.5, -40.77]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B230" position={[-109.95, 2.5, -38.42]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B229" position={[-109.71, 2.5, -36.08]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B228" position={[-109.48, 2.5, -33.74]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B224" position={[-104.18, 2.5, -41.36]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B225" position={[-103.95, 2.5, -39.02]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B226" position={[-103.72, 2.5, -36.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B227" position={[-103.49, 2.5, -34.33]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B221" position={[-101.92, 2.5, -41.58]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B220" position={[-101.69, 2.5, -39.24]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B219" position={[-101.46, 2.5, -36.9]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B218" position={[-101.23, 2.5, -34.56]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B253" position={[-103.97, 2.5, -59.56]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B252" position={[-103.74, 2.5, -57.21]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B251" position={[-103.51, 2.5, -54.87]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B250" position={[-103.28, 2.5, -52.53]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B269" position={[-127.46, 2.5, 40.94]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B268" position={[-127.69, 2.5, 38.59]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B267" position={[-127.92, 2.5, 36.25]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B266" position={[-128.15, 2.5, 33.91]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B265" position={[-128.38, 2.5, 31.57]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B264" position={[-128.61, 2.5, 29.23]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B263" position={[-128.84, 2.5, 26.88]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B256" position={[-125.28, 2.5, 40.72]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B257" position={[-125.51, 2.5, 38.38]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B258" position={[-125.74, 2.5, 36.04]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B259" position={[-125.97, 2.5, 33.69]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B260" position={[-126.2, 2.5, 31.35]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B261" position={[-126.43, 2.5, 29.01]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="B262" position={[-126.66, 2.5, 26.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C93" position={[-129, 2.5, -84.42]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C94" position={[-128.77, 2.5, -82.08]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C95" position={[-128.54, 2.5, -79.74]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C96" position={[-128.31, 2.5, -77.4]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C90" position={[-126.54, 2.5, -84.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C89" position={[-126.31, 2.5, -82.32]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C88" position={[-126.08, 2.5, -79.98]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C87" position={[-125.85, 2.5, -77.64]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C83" position={[-120.84, 2.5, -85.29]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C84" position={[-120.61, 2.5, -82.95]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C76" position={[-118.46, 2.5, -85.53]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C75" position={[-118.23, 2.5, -83.18]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C69" position={[-112.46, 2.5, -86.12]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C70" position={[-112.23, 2.5, -83.78]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C62" position={[-110.29, 2.5, -86.33]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C61" position={[-110.06, 2.5, -83.99]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C57" position={[-104.56, 2.5, -87.28]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C58" position={[-104.33, 2.5, -84.94]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C50" position={[-102.13, 2.5, -87.52]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C49" position={[-101.89, 2.5, -85.18]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C45" position={[-96.03, 2.5, -88.13]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C46" position={[-95.8, 2.5, -85.78]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C38" position={[-93.67, 2.5, -88.36]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C37" position={[-93.44, 2.5, -86.02]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C31" position={[-87.86, 2.5, -88.93]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C32" position={[-87.63, 2.5, -86.59]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C24" position={[-85.57, 2.5, -89.16]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C23" position={[-85.34, 2.5, -86.82]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C98" position={[-122.95, 2.5, -72.13]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C99" position={[-120.61, 2.5, -72.36]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C100" position={[-118.26, 2.5, -72.59]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C101" position={[-115.92, 2.5, -72.82]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="CIO2" position={[-113.58, 2.5, -73.05]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C103" position={[-111.24, 2.5, -73.28]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C104" position={[-108.89, 2.5, -73.52]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C105" position={[-106.55, 2.5, -73.75]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C106" position={[-104.21, 2.5, -73.98]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C107" position={[-101.87, 2.5, -74.21]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C108" position={[-99.52, 2.5, -74.44]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C109" position={[-97.18, 2.5, -74.67]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C110" position={[-94.84, 2.5, -74.9]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <instances.B2 name="C111" position={[-92.5, 2.5, -75.13]} rotation={[0, 0.1, 0]} scale={[0.98, 0.41, 0.98]} />
            <mesh
                name="Cube070"
                castShadow
                receiveShadow
                geometry={nodes.Cube070.geometry}
                material={materials['Material.006']}
                position={[-85.66, 2.5, 80.34]}
                rotation={[0, 0.1, 0]}
                scale={[24.31, 0.38, 24.31]}
            />
            <mesh
                name="Text066"
                castShadow
                receiveShadow
                geometry={nodes.Text066.geometry}
                material={nodes.Text066.material}
                position={[-94.72, 2.96, -24.62]}
                rotation={[-Math.PI, 1.47, -Math.PI]}
                scale={0.98}
            />
        </group>
    );
}

// useGLTF.preload('/stall.glb');
