/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Part2(props) {
    const { nodes, materials } = useGLTF('/startuptn/codissia/envbuilding.glb');
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={materials['Hall E']}
                position={[114.14, -2.73, 63.98]}
                rotation={[-0.04, 0.1, 0]}
                scale={[62.03, 29.78, 31.92]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                material={materials['Food Court']}
                position={[133.23, 6.77, -31.13]}
                scale={[37.51, 4.41, 37.51]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane007.geometry}
                material={materials['Material.020']}
                position={[-119.74, 17.4, -7.6]}
                rotation={[0, 0.11, 0]}
                scale={[29.49, 29.49, 59.36]}
            />
            <group position={[89.74, -2.73, -114.68]} rotation={[-3.1, -0.1, -3.14]} scale={[62.03, 29.78, 31.92]}>
                <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials['Hall D']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane002_1.geometry} material={materials['Material.046']} />
                <mesh castShadow receiveShadow geometry={nodes.Plane002_2.geometry} material={materials['Material.010']} />
            </group>
            <group position={[0.84, -10.06, 147.06]} rotation={[-Math.PI, -0.08, -Math.PI / 2]} scale={[-0.28, -28.68, -0.25]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials['metal structure']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials['Black  stange']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_3.geometry} material={materials['roof window']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_4.geometry} material={materials['Roof Plastic']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_5.geometry} material={materials['side roof']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_6.geometry} material={materials['Material.025']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_7.geometry} material={materials['Material.015']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_8.geometry} material={materials['Grass.001']} />
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_9.geometry} material={materials['cement support']} />
            </group>
            <group position={[-86.4, 5.4, -66.23]} rotation={[0, 0.12, 0]} scale={[-6.59, -3.28, -6.21]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials['Material.017']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials['Material.018']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube013_2.geometry} material={materials['Material.011']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube013_3.geometry} material={materials['Material.040']} />
                <mesh castShadow receiveShadow geometry={nodes.Cube013_4.geometry} material={materials['Material.027']} />
            </group>
        </group>
    );
}

// useGLTF.preload('/building.glb');
