/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { editable as e, SheetProvider } from '@theatre/r3f';
import React, { useRef, useMemo } from 'react';
import { useGLTF, Merged } from '@react-three/drei';

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/butterfly-orange-instances-transformed.glb');
  const instances = useMemo(
    () => ({
      Leaf: nodes.leaf,
    }),
    [nodes]
  );
  return (
    <Merged receiveShadow castShadow meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  );
}

function Model({ instances, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    '/butterfly-orange-instances-transformed.glb'
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <e.mesh
        uniqueName="ButterflyBody"
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.butterfly}
        position={[0, 0.95, 0]}
      >
        <e.mesh
          uniqueName="LLWing"
          castShadow
          receiveShadow
          geometry={nodes.LLwing.geometry}
          material={materials.butterfly}
          position={[-0.05, 0.07, -0.01]}
          rotation={[0, -0.13, 0]}
        />
        <e.mesh
          uniqueName="LUWing"
          castShadow
          receiveShadow
          geometry={nodes.LUwing.geometry}
          material={materials.butterfly}
          position={[-0.05, 0.09, -0.1]}
        />
        <e.mesh
          uniqueName="RLWing"
          castShadow
          receiveShadow
          geometry={nodes.RLwing.geometry}
          material={materials.butterfly}
          position={[0.07, 0.06, 0]}
          rotation={[0, -1.53, 0]}
        />
        <e.mesh
          uniqueName="RUWing"
          castShadow
          receiveShadow
          geometry={nodes.RUwing.geometry}
          material={materials.butterfly}
          position={[0.08, 0.08, -0.12]}
        />
      </e.mesh>
      <instances.Leaf position={[-0.29, -1.39, -0.17]} />
      <instances.Leaf
        position={[-2.38, -2.7, 0.49]}
        rotation={[0.07, -0.48, 0.48]}
        scale={0.74}
      />
      <instances.Leaf
        position={[-4.19, 0.58, -3.52]}
        rotation={[-1.08, -0.54, -1.1]}
        scale={0.56}
      />
      <instances.Leaf
        position={[-2.25, 1.6, -3.61]}
        rotation={[-0.29, 0.08, 0.52]}
        scale={0.29}
      />
      <instances.Leaf
        position={[-4.67, 1.9, -5]}
        rotation={[-2.38, -0.88, -2.11]}
        scale={0.38}
      />
      <instances.Leaf
        position={[-3.65, 2.53, -5.43]}
        rotation={[-2.29, 0.04, -2.73]}
        scale={0.29}
      />
      <instances.Leaf
        position={[-0.88, 2.51, -3.68]}
        rotation={[-1.01, 0.38, -0.01]}
        scale={0.51}
      />
      <instances.Leaf
        position={[-6.78, -0.39, -5.08]}
        rotation={[0, -1.26, 0]}
      />
      <instances.Leaf
        position={[-7.87, -1.51, -8.71]}
        rotation={[Math.PI, -0.83, Math.PI]}
        scale={0.74}
      />
      <instances.Leaf
        position={[-5.81, 0.9, -8.47]}
        rotation={[-2.8, -0.45, -2.27]}
        scale={0.56}
      />
      <instances.Leaf
        position={[-4.19, 2.62, -7.67]}
        rotation={[0.61, -0.93, 0.96]}
        scale={0.29}
      />
      <instances.Leaf
        position={[-4.77, 0.73, -10.95]}
        rotation={[3.08, -0.6, -2.24]}
        scale={0.38}
      />
      <instances.Leaf
        position={[-2.51, 1.82, -11.01]}
        rotation={[3.04, 1.08, -2.11]}
        scale={0.29}
      />
      <instances.Leaf
        position={[-3.21, 4.73, -7.83]}
        rotation={[2.94, -0.06, 2.92]}
        scale={0.72}
      />
      <instances.Leaf
        position={[-1.66, 0.19, -8.65]}
        rotation={[-2.38, -0.34, -2.84]}
        scale={0.82}
      />
      <instances.Leaf
        position={[0.84, -3.88, -6.44]}
        rotation={[-2.64, -0.66, -2.94]}
        scale={0.75}
      />
      <instances.Leaf
        position={[-2.55, -4.46, -6.38]}
        rotation={[-2.11, 0.61, -3.14]}
        scale={0.75}
      />
      <instances.Leaf
        position={[-0.44, -0.62, -4.86]}
        rotation={[-1.02, -0.6, -0.66]}
        scale={0.48}
      />
      <instances.Leaf
        position={[-6.43, -2.92, -4.07]}
        rotation={[-1.94, -0.24, -2.69]}
        scale={0.75}
      />
      <instances.Leaf
        position={[-0.47, -2.7, -7.19]}
        rotation={[-2.71, -1.05, 3.14]}
        scale={0.3}
      />
      <instances.Leaf
        position={[-4.09, -1.58, -7.21]}
        rotation={[-2.7, -0.06, -2.72]}
        scale={0.24}
      />
      <instances.Leaf
        position={[-4.47, 0.12, -10.33]}
        rotation={[-2.7, -0.32, -2.74]}
        scale={0.15}
      />
      <instances.Leaf
        position={[-5.19, -2, -7.97]}
        rotation={[-2.59, 0.03, -2.52]}
        scale={0.29}
      />
      <instances.Leaf
        position={[-3.73, -1.51, -9.23]}
        rotation={[-2.46, -0.41, -2.56]}
        scale={0.5}
      />
      <instances.Leaf
        position={[-12.08, 2.47, -8.52]}
        rotation={[-1.89, -0.3, -2.86]}
        scale={1.02}
      />
      <instances.Leaf
        position={[-9.07, 2.14, -9.66]}
        rotation={[-2.7, -0.53, -3.09]}
        scale={0.47}
      />
      <instances.Leaf
        position={[-7.09, 1.24, -12.61]}
        rotation={[-3.14, 0.25, -2.47]}
        scale={0.67}
      />
      <instances.Leaf
        position={[-3.32, 0.77, -3.94]}
        rotation={[0.04, -0.6, 0.84]}
        scale={0.35}
      />
      <instances.Leaf
        position={[-1.73, 0.05, -4.98]}
        rotation={[0, 0.16, 0.81]}
        scale={0.55}
      />
      <instances.Leaf
        position={[-0.99, -2.57, -4.93]}
        rotation={[-0.89, 0.49, -0.27]}
        scale={0.48}
      />
      <instances.Leaf
        position={[-3.52, -1.25, -2.4]}
        rotation={[-0.67, -0.82, -0.47]}
        scale={0.85}
      />
      <instances.Leaf
        position={[2.84, -5.96, -0.83]}
        rotation={[0.06, 0.58, -0.5]}
        scale={1.37}
      />
      <instances.Leaf
        position={[-3.74, -2.22, -3.38]}
        rotation={[-2.26, 1.01, 2.54]}
        scale={0.77}
      />
      <instances.Leaf
        position={[-4.48, -0.47, -3.64]}
        rotation={[-1.2, -0.95, -1.51]}
        scale={0.34}
      />
      <instances.Leaf
        position={[-3.73, 1.69, -4.13]}
        rotation={[-1.16, -1.05, -1.29]}
        scale={0.21}
      />
      <instances.Leaf
        position={[-5.39, -4.19, -0.68]}
        rotation={[0.92, -1.37, 0.54]}
        scale={0.43}
      />
      <instances.Leaf
        position={[-4.67, 5.67, -10.5]}
        rotation={[-1.98, 0.01, -2.87]}
        scale={0.72}
      />
      <instances.Leaf
        position={[-2.97, 3.36, -8.22]}
        rotation={[-3.1, -0.62, 2.9]}
        scale={0.31}
      />
      <instances.Leaf
        position={[-4.23, 2.51, -9.93]}
        rotation={[0.09, 0.62, 2.44]}
        scale={0.5}
      />
      <instances.Leaf
        position={[-4.44, 1.62, -9.27]}
        rotation={[3.08, 0.71, 0.93]}
        scale={0.99}
      />
      <instances.Leaf
        position={[-0.46, -5.77, -5.5]}
        rotation={[-0.8, 0.47, 1.78]}
        scale={0.75}
      />
      <instances.Leaf
        position={[-4.54, -1.69, -5.22]}
        rotation={[-0.8, 0.47, 1.78]}
        scale={0.24}
      />
      <instances.Leaf
        position={[-1.33, -1.49, -5.83]}
        rotation={[1.43, 0.95, 0.07]}
        scale={0.24}
      />
      <instances.Leaf
        position={[-3.2, -2.06, -7.12]}
        rotation={[1.43, 0.95, 0.07]}
        scale={0.57}
      />
      <instances.Leaf
        position={[-1.59, -3.52, -9.95]}
        rotation={[-0.56, -0.3, -1.33]}
        scale={1.12}
      />
      <instances.Leaf
        position={[-11.83, -3.59, -4.68]}
        rotation={[0.09, -0.87, -1.7]}
        scale={1.12}
      />
      <instances.Leaf
        position={[-8.93, -4.67, -2.94]}
        rotation={[0.6, -0.83, -0.24]}
        scale={0.69}
      />
      <instances.Leaf
        position={[-6.33, -7.66, -2.42]}
        rotation={[0.9, -0.4, -0.19]}
        scale={0.69}
      />
      <instances.Leaf
        position={[-0.94, -6.75, -7.62]}
        rotation={[0.9, -0.4, -0.19]}
        scale={0.69}
      />
      <instances.Leaf
        position={[-3.41, 2.2, -6.63]}
        rotation={[-2.05, -0.2, -2.58]}
        scale={0.47}
      />
      <instances.Leaf
        position={[-0.53, 1.1, -5.64]}
        rotation={[-1.41, -1.3, -3.07]}
        scale={0.73}
      />
      <instances.Leaf
        position={[-4.29, -4.83, -1.18]}
        rotation={[3.1, -0.01, -0.05]}
        scale={0.79}
      />
      <instances.Leaf
        position={[-0.43, -7.52, 2.14]}
        rotation={[0.03, -0.36, -0.92]}
        scale={1.02}
      />
      <instances.Leaf
        position={[-1.99, -6.24, 0.78]}
        rotation={[0.1, 0.11, -0.13]}
        scale={0.86}
      />
      <instances.Leaf
        position={[-11.05, -0.16, -7.58]}
        rotation={[0.38, 0.01, -0.11]}
        scale={1.13}
      />
      <instances.Leaf
        position={[-3.64, 1.43, -12.18]}
        rotation={[-0.33, -0.12, -0.53]}
        scale={1.25}
      />
      <instances.Leaf
        position={[-0.13, -2.86, -4.35]}
        rotation={[1.02, -0.84, -1.9]}
        scale={0.74}
      />
    </group>
  );
}

useGLTF.preload('/butterfly-orange-instances-transformed.glb');
